name: market-pxg
version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src
    env_file: 
      - ./.env
    environment:
      - NODE_ENV=development    
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  redis: # Serviço Redis
    image: redis:alpine # Usando uma versão leve do Redis
    ports:
      - "6379:6379" # Porta padrão do Redis
    volumes:
      - redisdata:/data # Persistência de dados (opcional)


volumes:
  pgdata:
  redisdata: 