# Imagem oficial do Node.js 20
FROM node:20

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /src

# Copie o arquivo package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências do Node.js
RUN npm install

# Copie o restante do código para o contêiner
COPY . .

# Exponha a porta 3000 para acessar a aplicação
EXPOSE 3000

# Comando para rodar a aplicação (ajuste conforme necessário)
CMD ["npm", "run", "dev"]